import { defineType } from 'sanity';

export default defineType({
  name: 'aiSummary',
  title: 'AI Summary',
  type: 'document',
  fields: [
    {
      name: 'contentId',
      title: 'Content ID',
      type: 'string',
      description: 'ID of the original content this summary belongs to',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'contentType',
      title: 'Content Type',
      type: 'string',
      options: {
        list: [
          { title: 'Article', value: 'article' },
          { title: 'Interview', value: 'interview' },
          { title: 'Publication', value: 'publication' },
        ],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Content Slug',
      type: 'string',
      description: 'Slug of the original content',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'shortSummary',
      title: 'Short Summary',
      type: 'text',
      description: 'Brief 2-3 sentence summary',
      validation: (Rule) => Rule.required().max(500),
    },
    {
      name: 'mediumSummary',
      title: 'Detailed Summary',
      type: 'text',
      description: 'Comprehensive 4-6 paragraph summary',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'keyPoints',
      title: 'Key Points',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Important insights and takeaways',
      validation: (Rule) => Rule.required().min(3).max(10),
    },
    {
      name: 'aiGeneratedTags',
      title: 'AI Generated Tags',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Tags generated by AI analysis',
    },
    {
      name: 'sentiment',
      title: 'Sentiment',
      type: 'string',
      options: {
        list: [
          { title: 'Positive', value: 'positive' },
          { title: 'Neutral', value: 'neutral' },
          { title: 'Negative', value: 'negative' },
        ],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'topics',
      title: 'Topics',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Main topics covered in the content',
    },
    {
      name: 'generatedAt',
      title: 'Generated At',
      type: 'datetime',
      description: 'When the summary was generated',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Completed', value: 'completed' },
          { title: 'Failed', value: 'failed' },
          { title: 'Processing', value: 'processing' },
        ],
      },
      initialValue: 'completed',
      validation: (Rule) => Rule.required(),
    },
  ],
  preview: {
    select: {
      title: 'contentId',
      subtitle: 'contentType',
      status: 'status',
    },
    prepare(selection) {
      const { title, subtitle, status } = selection;
      return {
        title: `AI Summary: ${title}`,
        subtitle: `${subtitle} - ${status}`,
      };
    },
  },
});
